contact_links:
  - name: Question or Support Request
    url: https://github.com/jarun/nnn/discussions
    about: If you have a question, need support or want to discuss something then please open a discussion thread.
